### ISSUE TITLE
Unable to open .pt3 files

### ISSUE THREAD

**Issue by paulmueller** [dwaithe/FCS_viewer#3]
Dear Dominic,

FCSViewer is having problems opening certain .pt3 files. Could you please check if this can be fixed?

I am referencing the corresponding issue that came up with PyCorrFit:
https://github.com/paulmueller/PyCorrFit/issues/89

The files that do not work were uploaded by Pierre @phubert52 .

 https://bfs.imm.cnrs.fr/bfs/files/a3f05c53f4109afd3d01f3e17ef49b0d/ATTO488.pt3
 https://bfs.imm.cnrs.fr/bfs/files/14b35877e62570d20ec195ed89bd4d05/Point_4.pt3 

Thanks,
Paul

**Comment by dwaithe** [comment]
Hi Paul,The .pt3 files worked in my current version of my software. I do not recognise your error message. If the problem is a memory issue it might be that the array operations are too large in the correlation algorithm, I sometime ago started compiling my software to be 64-bit and this fixed the problem. Are you 32-bit or 64-bit.Best,Dominic.
Date: Tue, 13 Jan 2015 07:41:13 -0800

**Comment by paulmueller** [comment]
Dear Dominic,

indeed, the file is larger than the example file in your repository and my build machines are 32bit. But I am running a 64bit linux system. You will find the error message that I get below. 

Could it be that the code on GitHub is not up to date? 

What command do you use to compile your code. I use
    
    cython -a fib4.pyx
    gcc -shared -pthread -fPIC -fwrapv -O2 -Wall -fno-strict-aliasing -I/usr/include/python2.7 -o fib4.so fib4.c

Thanks for your reply,
Paul


    $ python v02/FCSdataViewerMain.py 
    /home/paul/repos/FCS_viewer/vefcsv/local/lib/python2.7/site-packages/lmfit/ui/__init__.py:23:   UserWarning: lmfit.Fitter will use basic mode, not IPython: need IPython2.
      warnings.warn(_ipy_msg1)
    /usr/lib/python2.7/dist-packages/gtk-2.0/gtk/__init__.py:127: RuntimeWarning: PyOS_InputHook is not available for interactive use of PyGTK
      set_interactive(1)
    Traceback (most recent call last):
      File "v02/FCSdataViewerMain.py", line 708, in showDialog
        picoObject(filepath);
      File "v02/FCSdataViewerMain.py", line 317, in __init__
        self.processData();
      File "v02/FCSdataViewerMain.py", line 360, in processData
        self.photonDecayCh2,self.decayScale2 = delayTime2bin(self.dTimeArr,self.subChanArr,2,self.winInt)
          File "v02/FCSdataViewerMain.py", line 276, in delayTime2bin
        minDecayTime = np.min(decayTimeCh).astype(np.int32)
      File "/usr/lib/python2.7/dist-packages/numpy/core/fromnumeric.py", line 2214, in amin
    out=out, keepdims=keepdims)
      File "/usr/lib/python2.7/dist-packages/numpy/core/_methods.py", line 21, in _amin
    out=out, keepdims=keepdims)
    ValueError: zero-size array to reduction operation minimum which has no identity

**Comment by dwaithe** [comment]
Hi, 
I have committed the latest version of my software. I am not such a great fan of github (yet) so I am sorry my commits are very out-of-date. I have been improving the software a lot in the mean-time. I will commit more often from now on. I think your error is caused by the .pt3 file being only single channel, though I am not sure. The latest functions work with this file so I think if you update delayTime2bin you will have more luck. I hope there are not too many changes in this commit. I am still learning the best way to right software so I do make some structural changes from time to time. Advice is always welcome.



I compile my code a different way:

I run: python setup.py build

setup.py contents:

from distutils.core import setup
from distutils.extension import Extension
from Cython.Distutils import build_ext
import numpy

setup(
    include_dirs=[numpy.get_include()] ,cmdclass = {'build_ext': build_ext},
    ext_modules = [Extension("fib4", ["fib4.pyx"])]
)

Best,
Dominic.

**Comment by paulmueller** [comment]
Thanks for the commit. I can now open the file with FCS_Viewer.

Best,
Paul
